spring.application.name=financialdataprocessing
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/financedata
spring.datasource.username="Your username here"
spring.datasource.password="your password here"
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect